version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:latest
    ports:
      - "8080:8080"
    volumes:
      - $PWD/janky:/var/jenkins-course
    networks:
      - net
networks:
  net:
